### ISSUE TITLE
Error: key can't be empty

### ISSUE THREAD

**Issue by dreamking60** [TokTok/jvm-toxcore-c#102]
I wonder use the tox in my own written chat. Firstly, I use maven but it can't find any resources. Then I come here and git clone the whole  repository. I wonder how to add it in my project. I try to build it on my PC, but it seems failed.

I use the command
```
sbt -D java.security.manager compile
```

The result is as the following. I don't know what the error and why this error happend.
```
java.lang.IllegalArgumentException: key can't be empty
        at java.base/java.lang.System.checkKey(System.java:1098)
        at java.base/java.lang.System.setProperty(System.java:1041)
        at scala.sys.SystemProperties.$anonfun$addOne$1(SystemProperties.scala:53)
        at scala.sys.SystemProperties.wrapAccess(SystemProperties.scala:56)
        at scala.sys.SystemProperties.addOne(SystemProperties.scala:53)
        at scala.sys.SystemProperties.addOne(SystemProperties.scala:30)
        at scala.collection.mutable.Growable.$plus$eq(Growable.scala:36)
        at scala.collection.mutable.Growable.$plus$eq$(Growable.scala:36)
        at scala.collection.mutable.AbstractMap.$plus$eq(Map.scala:265)
        at xsbt.boot.Configuration$.setProperty(Configuration.scala:52)
        at xsbt.boot.Configuration$.find(Configuration.scala:39)
        at xsbt.boot.Launch$.apply(Launch.scala:30)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.IllegalArgumentException: key can't be empty
```

**Comment by iphydf** [comment]
We've removed sbt. Try again with the gradle build.
